husky test

diff --git a/frontend/.husky/pre-commit b/frontend/.husky/pre-commit
--- a/frontend/.husky/pre-commit
+++ b/frontend/.husky/pre-commit
@@ -1,17 +1,22 @@
-# have to do this because .husky is not in the parent directory
+#!/bin/sh
 cd frontend
 
-# linting
-pnpm run lint || {
-  echo "Linting failed. Commit aborted."
-  exit 1
-}
+# Check if there are any changes in the frontend directory
+if git diff --cached --name-only | grep -q '^frontend/src/'; then
+  # linting
+  pnpm run lint || {
+    echo "Linting failed. Commit aborted."
+    exit 1
 
-# formatting
-pnpm run format || {
-  echo "Formatting failed. Commit aborted."
-  exit 1
-}
+  }
+  # formatting
+  pnpm run format || {
+    echo "Formatting failed. Commit aborted."
+    exit 1
+  }
 
-# adding the formatted changes
-git add .
+  # adding the formatted changes
+  git add .
+else
+  echo "No changes in the frontend directory. Skipping linting and formatting."
+fi
