husky test with formatting

diff --git a/frontend/.husky/pre-commit b/frontend/.husky/pre-commit
--- a/frontend/.husky/pre-commit
+++ b/frontend/.husky/pre-commit
@@ -4,3 +4,9 @@ pnpm run lint || {
   echo "Linting failed. Commit aborted."
   exit 1
 }
+
+# formatting
+pnpm run format && git add . || {
+  echo "Formatting failed. Commit aborted."
+  exit 1
+}
